name: example-environment
channels:
  - conda-forge
  - biconda
  - defaults
dependencies:
  - python=3.9
  - r-base=4.0
  - plotly
  - pandas
  - seaborn
  - matplotlib
  - scikit-learn
  - numpy
  - scipy
  - statsmodels
  - r-dplyr
  - r-ggplot2
  - r-reshape2
  - r-tidyverse
  - r-plotlyr
  - r-stringr
